create table dw_category_info
(
  categorytreeid   UInt8,
  deptlevelid      UInt32,
  categoryid       String,
  categoryname     String,
  mid_categoryid   String,
  mid_categoryname String,
  h_categoryid     String,
  h_categoryname   String
)
  engine = Log;

create table dw_good_info
(
  buid             String,
  categoryid       String,
  categorytreeid   UInt8,
  sysgoodsid       UInt8,
  goodsid          UInt32,
  goodscode        UInt32,
  goodsname        String,
  barcode          String,
  unitname         String,
  inbuid           String,
  producingarea    String,
  adviceprice      String,
  advicecost       String,
  addrate          String,
  brandid          UInt32,
  categoryname     String,
  mid_categoryid   String,
  mid_categoryname String,
  h_categoryid     String,
  h_categoryname   String
)
  engine = Log;

create table dw_shop_info
(
  shopid            String,
  shopcode          String,
  shopname          String,
  buid              String,
  inbuid            String,
  shopformid        UInt16,
  shopstatus        UInt16,
  buname            String,
  categorytreeid    UInt32,
  payshopid         String,
  regionid          UInt16,
  provinces_regions String,
  propertype        String,
  dctype            String
)
  engine = Log;

create table dw_vender_info
(
  buid              String,
  venderid          String,
  vendername        String,
  vendercode        String,
  parent_buid       String,
  parent_venderid   String,
  parent_vendername String
)
  engine = Log;

create table fct_rpt_dc_shop_sku_vender_day
(
  stat_year      UInt16,
  stat_month     UInt32,
  stat_day       Date,
  buid           String,
  dc_shop_id     String,
  dctype         UInt8,
  shop_id        String,
  shopformid     UInt8,
  categorytreeid UInt8,
  categoryid     String,
  logistics      UInt8,
  venderid       String,
  datasource     UInt8,
  rpt_qty        Decimal (18, 4),
  rpt_boxes      Decimal (18, 4),
  rpt_cost       Decimal (18, 4),
  rpt_taxcost    Decimal (18, 4)
)
  engine = MergeTree
    PARTITION BY toYYYYMM(stat_day) ORDER BY (stat_day, dc_shop_id)
    SETTINGS index_granularity = 8192;

create table fct_rpt_dc_shop_sku_vender_mon
(
  stat_year      UInt16,
  stat_month     UInt32,
  buid           String,
  dc_shop_id     String,
  dctype         UInt8,
  shop_id        String,
  shopformid     UInt8,
  categorytreeid UInt8,
  categoryid     String,
  logistics      UInt8,
  venderid       String,
  datasource     UInt8,
  rpt_qty        Decimal (18, 4),
  rpt_boxes      Decimal (18, 4),
  rpt_cost       Decimal (18, 4),
  rpt_taxcost    Decimal (18, 4)
)
  engine = MergeTree
    PARTITION BY stat_month ORDER BY (stat_month, dc_shop_id)
    SETTINGS index_granularity = 8192;

create table fct_rsl_dc_shop_vender_day
(
  stat_year                   UInt16,
  stat_month                  UInt32,
  stat_day                    Date,
  out_buid                    String,
  shop_id                     String,
  logistics                   UInt16,
  categoryid                  String,
  venderid                    String,
  dc_type                     UInt8,
  shopformid                  UInt8,
  rsl_cost                    Decimal (18, 4),
  rsl_boxes                   Decimal (18, 4),
  rsl_qty                     Decimal (18, 4),
  rsl_drygood_cost            Decimal (18, 4),
  rsl_drygood_boxes           Decimal (18, 4),
  rsl_drygood_qty             Decimal (18, 4),
  rsl_fresh_cost              Decimal (18, 4),
  rsl_fresh_boxes             Decimal (18, 4),
  rsl_fresh_qty               Decimal (18, 4),
  rsl_drygood_supshop_cost    Decimal (18, 4),
  rsl_drygood_supshop_boxes   Decimal (18, 4),
  rsl_drygood_supshop_qty     Decimal (18, 4),
  rsl_drygood_smallshop_cost  Decimal (18, 4),
  rsl_drygood_smallshop_boxes Decimal (18, 4),
  rsl_drygood_smallshop_qty   Decimal (18, 4),
  rsl_fresh_supshop_cost      Decimal (18, 4),
  rsl_fresh_supshop_boxes     Decimal (18, 4),
  rsl_fresh_supshop_qty       Decimal (18, 4),
  rsl_fresh_smallshop_cost    Decimal (18, 4),
  rsl_fresh_smallshop_boxes   Decimal (18, 4),
  rsl_fresh_smallshop_qty     Decimal (18, 4)
)
  engine = MergeTree
    PARTITION BY toYYYYMM(stat_day) ORDER BY (shop_id, venderid)
    SETTINGS index_granularity = 8192;

create table fct_rt_dc_shop_day
(
  stat_year                  UInt16,
  stat_month                 UInt32,
  stat_day                   Date,
  out_buid                   String,
  out_shop_id                String,
  in_shop_id                 String,
  datasource                 UInt8,
  logistics                  UInt8,
  buntype                    UInt8,
  dctype                     UInt8,
  shopformid                 UInt8,
  rt_qty                     Decimal (18, 4),
  rt_cost                    Decimal (18, 4),
  rt_taxcost                 Decimal (18, 4),
  rt_shops                   String,
  rt_drygood_qty             Decimal (18, 4),
  rt_drygood_cost            Decimal (18, 4),
  rt_drygood_boxes           Decimal (18, 4),
  rt_drygood_shops           String,
  rt_fresh_qty               Decimal (18, 4),
  rt_fresh_cost              Decimal (18, 4),
  rt_fresh_shops             String,
  rt_supshop_cost            Decimal (18, 4),
  rt_supshop_qty             Decimal (18, 4),
  rt_supshop_shops           String,
  rt_smallshop_cost          Decimal (18, 4),
  rt_smallshop_qty           Decimal (18, 4),
  rt_smallshop_shops         String,
  rt_dc_cost                 Decimal (18, 4),
  rt_dc_qty                  Decimal (18, 4),
  rt_drygood_supshop_cost    Decimal (18, 4),
  rt_drygood_supshop_qty     Decimal (18, 4),
  rt_drygood_supshop_boxes   Decimal (18, 4),
  rt_drygood_supshop_shops   String,
  rt_drygood_smallshop_cost  Decimal (18, 4),
  rt_drygood_smallshop_qty   Decimal (18, 4),
  rt_drygood_smallshop_boxes Decimal (18, 4),
  rt_drygood_smallshop_shops String,
  rt_drygood_dc_cost         Decimal (18, 4),
  rt_drygood_dc_qty          Decimal (18, 4),
  rt_drygood_dc_boxes        Decimal (18, 4),
  rt_drygood_dc_shops        String,
  rt_fresh_supshop_cost      Decimal (18, 4),
  rt_fresh_supshop_qty       Decimal (18, 4),
  rt_fresh_supshop_shops     String,
  rt_fresh_smallshop_cost    Decimal (18, 4),
  rt_fresh_smallshop_qty     Decimal (18, 4),
  rt_fresh_smallshop_shops   String,
  rt_fresh_dc_cost           Decimal (18, 4),
  rt_fresh_dc_qty            Decimal (18, 4)
)
  engine = MergeTree
    PARTITION BY toYYYYMM(stat_day) ORDER BY (stat_day, out_shop_id)
    SETTINGS index_granularity = 8192;

create table fct_rt_dc_shop_sku_vender_day
(
  stat_year                  UInt16,
  stat_month                 UInt32,
  stat_day                   Date,
  out_buid                   String,
  out_shop_id                String,
  in_shop_id                 String,
  datasource                 UInt8,
  venderid                   String,
  categorytreeid             UInt8,
  categoryid                 String,
  logistics                  UInt8,
  buntype                    UInt8,
  dctype                     UInt8,
  shopformid                 UInt8,
  rt_qty                     Decimal (18, 4),
  rt_cost                    Decimal (18, 4),
  rt_taxcost                 Decimal (18, 4),
  rt_shops                   String,
  rt_drygood_qty             Decimal (18, 4),
  rt_drygood_cost            Decimal (18, 4),
  rt_drygood_boxes           Decimal (18, 4),
  rt_drygood_shops           String,
  rt_fresh_qty               Decimal (18, 4),
  rt_fresh_cost              Decimal (18, 4),
  rt_fresh_shops             String,
  rt_supshop_cost            Decimal (18, 4),
  rt_supshop_qty             Decimal (18, 4),
  rt_supshop_shops           String,
  rt_smallshop_cost          Decimal (18, 4),
  rt_smallshop_qty           Decimal (18, 4),
  rt_smallshop_shops         String,
  rt_dc_cost                 Decimal (18, 4),
  rt_dc_qty                  Decimal (18, 4),
  rt_drygood_supshop_cost    Decimal (18, 4),
  rt_drygood_supshop_qty     Decimal (18, 4),
  rt_drygood_supshop_boxes   Decimal (18, 4),
  rt_drygood_supshop_shops   String,
  rt_drygood_smallshop_cost  Decimal (18, 4),
  rt_drygood_smallshop_qty   Decimal (18, 4),
  rt_drygood_smallshop_boxes Decimal (18, 4),
  rt_drygood_smallshop_shops String,
  rt_drygood_dc_cost         Decimal (18, 4),
  rt_drygood_dc_qty          Decimal (18, 4),
  rt_drygood_dc_boxes        Decimal (18, 4),
  rt_drygood_dc_shops        String,
  rt_fresh_supshop_cost      Decimal (18, 4),
  rt_fresh_supshop_qty       Decimal (18, 4),
  rt_fresh_supshop_shops     String,
  rt_fresh_smallshop_cost    Decimal (18, 4),
  rt_fresh_smallshop_qty     Decimal (18, 4),
  rt_fresh_smallshop_shops   String,
  rt_fresh_dc_cost           Decimal (18, 4),
  rt_fresh_dc_qty            Decimal (18, 4)
)
  engine = MergeTree
    PARTITION BY toYYYYMM(stat_day) ORDER BY (stat_day, out_shop_id)
    SETTINGS index_granularity = 8192;

create table fct_rt_dc_shop_sku_vender_day_ti
(
  stat_year   UInt16,
  stat_month  UInt32,
  stat_day    Date,
  out_buid    String,
  out_shop_id String,
  dctype      UInt8,
  in_shop_id  String,
  shopformid  UInt8,
  goodsid     UInt32,
  category_id String,
  venderid    String,
  logistics   UInt8,
  buntype     UInt8,
  datasource  UInt8,
  rt_boxes    Decimal (18, 4),
  rt_qty      Decimal (18, 4),
  rt_cost     Decimal (18, 4),
  rt_taxcost  Decimal (18, 4)
)
  engine = Log;

create table fct_rt_dc_shop_sku_vender_mon
(
  stat_year                  UInt16,
  stat_month                 UInt32,
  out_buid                   String,
  out_shop_id                String,
  in_shop_id                 String,
  datasource                 UInt8,
  venderid                   String,
  categorytreeid             UInt8,
  categoryid                 String,
  logistics                  UInt8,
  buntype                    UInt8,
  dctype                     UInt8,
  shopformid                 UInt8,
  rt_qty                     Decimal (18, 4),
  rt_cost                    Decimal (18, 4),
  rt_taxcost                 Decimal (18, 4),
  rt_shops                   String,
  rt_drygood_qty             Decimal (18, 4),
  rt_drygood_cost            Decimal (18, 4),
  rt_drygood_boxes           Decimal (18, 4),
  rt_drygood_shops           String,
  rt_fresh_qty               Decimal (18, 4),
  rt_fresh_cost              Decimal (18, 4),
  rt_fresh_shops             String,
  rt_supshop_cost            Decimal (18, 4),
  rt_supshop_qty             Decimal (18, 4),
  rt_supshop_shops           String,
  rt_smallshop_cost          Decimal (18, 4),
  rt_smallshop_qty           Decimal (18, 4),
  rt_smallshop_shops         String,
  rt_dc_cost                 Decimal (18, 4),
  rt_dc_qty                  Decimal (18, 4),
  rt_drygood_supshop_cost    Decimal (18, 4),
  rt_drygood_supshop_qty     Decimal (18, 4),
  rt_drygood_supshop_boxes   Decimal (18, 4),
  rt_drygood_supshop_shops   String,
  rt_drygood_smallshop_cost  Decimal (18, 4),
  rt_drygood_smallshop_qty   Decimal (18, 4),
  rt_drygood_smallshop_boxes Decimal (18, 4),
  rt_drygood_smallshop_shops String,
  rt_drygood_dc_cost         Decimal (18, 4),
  rt_drygood_dc_qty          Decimal (18, 4),
  rt_drygood_dc_boxes        Decimal (18, 4),
  rt_drygood_dc_shops        String,
  rt_fresh_supshop_cost      Decimal (18, 4),
  rt_fresh_supshop_qty       Decimal (18, 4),
  rt_fresh_supshop_shops     String,
  rt_fresh_smallshop_cost    Decimal (18, 4),
  rt_fresh_smallshop_qty     Decimal (18, 4),
  rt_fresh_smallshop_shops   String,
  rt_fresh_dc_cost           Decimal (18, 4),
  rt_fresh_dc_qty            Decimal (18, 4),
  rt_outshop_cost            Decimal (18, 4),
  rt_outshop_boxes           Decimal (18, 4),
  rt_outshop_qty             Decimal (18, 4)
)
  engine = MergeTree
    PARTITION BY stat_month ORDER BY out_shop_id
    SETTINGS index_granularity = 8192;

create table fct_rt_dc_shop_sku_vender_mon_ti
(
  stat_year                  UInt16,
  stat_month                 UInt32,
  out_buid                   String,
  out_shop_id                String,
  in_shop_id                 String,
  datasource                 UInt8,
  venderid                   String,
  categorytreeid             UInt8,
  categoryid                 String,
  logistics                  UInt8,
  buntype                    UInt8,
  dctype                     UInt8,
  shopformid                 UInt8,
  rt_qty                     Decimal (18, 4),
  rt_cost                    Decimal (18, 4),
  rt_taxcost                 Decimal (18, 4),
  rt_shops                   String,
  rt_drygood_qty             Decimal (18, 4),
  rt_drygood_cost            Decimal (18, 4),
  rt_drygood_boxes           Decimal (18, 4),
  rt_drygood_shops           String,
  rt_fresh_qty               Decimal (18, 4),
  rt_fresh_cost              Decimal (18, 4),
  rt_fresh_shops             String,
  rt_supshop_cost            Decimal (18, 4),
  rt_supshop_qty             Decimal (18, 4),
  rt_supshop_shops           String,
  rt_smallshop_cost          Decimal (18, 4),
  rt_smallshop_qty           Decimal (18, 4),
  rt_smallshop_shops         String,
  rt_dc_cost                 Decimal (18, 4),
  rt_dc_qty                  Decimal (18, 4),
  rt_drygood_supshop_cost    Decimal (18, 4),
  rt_drygood_supshop_qty     Decimal (18, 4),
  rt_drygood_supshop_boxes   Decimal (18, 4),
  rt_drygood_supshop_shops   String,
  rt_drygood_smallshop_cost  Decimal (18, 4),
  rt_drygood_smallshop_qty   Decimal (18, 4),
  rt_drygood_smallshop_boxes Decimal (18, 4),
  rt_drygood_smallshop_shops String,
  rt_drygood_dc_cost         Decimal (18, 4),
  rt_drygood_dc_qty          Decimal (18, 4),
  rt_drygood_dc_boxes        Decimal (18, 4),
  rt_drygood_dc_shops        String,
  rt_fresh_supshop_cost      Decimal (18, 4),
  rt_fresh_supshop_qty       Decimal (18, 4),
  rt_fresh_supshop_shops     String,
  rt_fresh_smallshop_cost    Decimal (18, 4),
  rt_fresh_smallshop_qty     Decimal (18, 4),
  rt_fresh_smallshop_shops   String,
  rt_fresh_dc_cost           Decimal (18, 4),
  rt_fresh_dc_qty            Decimal (18, 4)
)
  engine = Log;

CREATE VIEW dw_hr.vw_dw_buinfo (buid String, buname String, mapping_buid String, mapping_buname String, categorytreeid UInt8) AS
  SELECT jb.buid,
         jb.buname,
         multiIf(jb.buid = '32', '15', jb.buid)   AS mapping_buid,
         multiIf(jb.buid = '32', '东北', jb.buname) AS mapping_buname,
         toUInt8(jb.categorytreeid)               AS categorytreeid
  FROM ods_hr.jv_buinfo AS jb;

CREATE VIEW dw_hr.vw_fct_rpt_dc_shop_sku_vender_day (stat_year UInt16, stat_month UInt32, stat_day Date, out_buname String, provinces_regions String, dc_shop_id String, out_shopname String, rpt_dctype String, shop_id String, shopformid_type String, venderid String, p_venderid String, p_vendernm String, rpt_datasource String, categoryid String, categoryname String, mid_categoryid String, mid_categoryname String, h_categoryid String, h_categoryname String, rpt_qty Decimal (18, 4), rpt_boxes Decimal (18, 4), rpt_cost Decimal (18, 4), rpt_taxcost Decimal (18, 4)) AS
  SELECT frdssvd.stat_year,
         frdssvd.stat_month,
         frdssvd.stat_day,
         dictGetString('dw_buinfo', 'buname', tuple(buid))                                                   AS out_buname,
         dictGetString('dw_shop', 'provinces_regions', tuple(dc_shop_id))                                    AS provinces_regions,
         frdssvd.dc_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(dc_shop_id))                                             AS out_shopname,
         multiIf(frdssvd.dctype = 1, '干货', frdssvd.dctype = 2, '生鲜', '未知')                                   AS rpt_dctype,
         frdssvd.shop_id,
         multiIf(frdssvd.shopformid = 1, '大超', frdssvd.shopformid = 2, '小业态', frdssvd.shopformid = 3, '标超',
                 frdssvd.shopformid = 4, '便利店', frdssvd.shopformid = 5, '仓间',
                 '未知')                                                                                       AS shopformid_type,
         frdssvd.venderid,
         dictGetString('dw_vender_info', 'parent_venderid', (buid,
                                                             venderid))                                      AS p_venderid,
         dictGetString('dw_vender_info', 'parent_vendername', (buid,
                                                               venderid))                                    AS p_vendernm,
         multiIf(frdssvd.datasource = 1, '全国', frdssvd.datasource = 2, '香港', frdssvd.datasource = 3, '苏果',
                 frdssvd.datasource = 4, 'OLE',
                 '未知')                                                                                       AS rpt_datasource,
         frdssvd.categoryid,
         dictGetString('dw_category_info', 'categoryname', (frdssvd.categorytreeid,
                                                            frdssvd.categoryid))                             AS categoryname,
         dictGetString('dw_category_info', 'mid_categoryid', (frdssvd.categorytreeid,
                                                              frdssvd.categoryid))                           AS mid_categoryid,
         dictGetString('dw_category_info', 'mid_categoryname', (frdssvd.categorytreeid,
                                                                frdssvd.categoryid))                         AS mid_categoryname,
         dictGetString('dw_category_info', 'h_categoryid', (frdssvd.categorytreeid,
                                                            frdssvd.categoryid))                             AS h_categoryid,
         dictGetString('dw_category_info', 'h_categoryname', (frdssvd.categorytreeid,
                                                              frdssvd.categoryid))                           AS h_categoryname,
         frdssvd.rpt_qty,
         frdssvd.rpt_boxes,
         frdssvd.rpt_cost,
         frdssvd.rpt_taxcost
  FROM dw_hr.fct_rpt_dc_shop_sku_vender_day AS frdssvd;

CREATE VIEW dw_hr.vw_fct_rpt_dc_shop_sku_vender_mon (stat_year UInt16, stat_month UInt32, out_buname String, provinces_regions String, dc_shop_id String, out_shopname String, rpt_dctype String, shop_id String, shopformid_type String, venderid String, p_venderid String, p_vendernm String, rpt_datasource String, categoryid String, categoryname String, mid_categoryid String, mid_categoryname String, h_categoryid String, h_categoryname String, rpt_qty Decimal (18, 4), rpt_boxes Decimal (18, 4), rpt_cost Decimal (18, 4), rpt_taxcost Decimal (18, 4)) AS
  SELECT frdssvd.stat_year,
         frdssvd.stat_month,
         dictGetString('dw_buinfo', 'buname', tuple(buid))                                                   AS out_buname,
         dictGetString('dw_shop', 'provinces_regions', tuple(dc_shop_id))                                    AS provinces_regions,
         frdssvd.dc_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(dc_shop_id))                                             AS out_shopname,
         multiIf(frdssvd.dctype = 1, '干货', frdssvd.dctype = 2, '生鲜', '未知')                                   AS rpt_dctype,
         frdssvd.shop_id,
         multiIf(frdssvd.shopformid = 1, '大超', frdssvd.shopformid = 2, '小业态', frdssvd.shopformid = 3, '标超',
                 frdssvd.shopformid = 4, '便利店', frdssvd.shopformid = 5, '仓间',
                 '未知')                                                                                       AS shopformid_type,
         frdssvd.venderid,
         dictGetString('dw_vender_info', 'parent_venderid', (buid,
                                                             venderid))                                      AS p_venderid,
         dictGetString('dw_vender_info', 'parent_vendername', (buid,
                                                               venderid))                                    AS p_vendernm,
         multiIf(frdssvd.datasource = 1, '全国', frdssvd.datasource = 2, '香港', frdssvd.datasource = 3, '苏果',
                 frdssvd.datasource = 4, 'OLE',
                 '未知')                                                                                       AS rpt_datasource,
         frdssvd.categoryid,
         dictGetString('dw_category_info', 'categoryname', (frdssvd.categorytreeid,
                                                            frdssvd.categoryid))                             AS categoryname,
         dictGetString('dw_category_info', 'mid_categoryid', (frdssvd.categorytreeid,
                                                              frdssvd.categoryid))                           AS mid_categoryid,
         dictGetString('dw_category_info', 'mid_categoryname', (frdssvd.categorytreeid,
                                                                frdssvd.categoryid))                         AS mid_categoryname,
         dictGetString('dw_category_info', 'h_categoryid', (frdssvd.categorytreeid,
                                                            frdssvd.categoryid))                             AS h_categoryid,
         dictGetString('dw_category_info', 'h_categoryname', (frdssvd.categorytreeid,
                                                              frdssvd.categoryid))                           AS h_categoryname,
         frdssvd.rpt_qty,
         frdssvd.rpt_boxes,
         frdssvd.rpt_cost,
         frdssvd.rpt_taxcost
  FROM dw_hr.fct_rpt_dc_shop_sku_vender_mon AS frdssvd;

CREATE VIEW dw_hr.vw_fct_rsl_dc_shop_vender_day (stat_year UInt16, stat_month UInt32, stat_day Date, out_buid String, buname String, shop_id String, shopname String, provinces_regions String, categorytreeid UInt32, rsl_logistics String, categoryid String, categoryname String, mid_categoryid String, mid_categoryname String, h_categoryid String, h_categoryname String, venderid String, vendername String, parent_venderid String, parent_vendername String, rsl_dctype String, rsl_shopformid String, rsl_cost Decimal (18, 4), rsl_boxes Decimal (18, 4), rsl_qty Decimal (18, 4), rsl_drygood_cost Decimal (18, 4), rsl_drygood_boxes Decimal (18, 4), rsl_drygood_qty Decimal (18, 4), rsl_fresh_cost Decimal (18, 4), rsl_fresh_boxes Decimal (18, 4), rsl_fresh_qty Decimal (18, 4), rsl_drygood_supshop_cost Decimal (18, 4), rsl_drygood_supshop_boxes Decimal (18, 4), rsl_drygood_supshop_qty Decimal (18, 4), rsl_drygood_smallshop_cost Decimal (18, 4), rsl_drygood_smallshop_boxes Decimal (18, 4), rsl_drygood_smallshop_qty Decimal (18, 4), rsl_fresh_supshop_cost Decimal (18, 4), rsl_fresh_supshop_boxes Decimal (18, 4), rsl_fresh_supshop_qty Decimal (18, 4), rsl_fresh_smallshop_cost Decimal (18, 4), rsl_fresh_smallshop_boxes Decimal (18, 4)) AS
  SELECT stat_year,
         stat_month,
         stat_day,
         out_buid,
         dictGetString('dw_buinfo', 'buname', tuple(out_buid))                                        AS buname,
         shop_id,
         dictGetString('dw_shop', 'shopname', tuple(shop_id))                                         AS shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(shop_id))                                AS provinces_regions,
         dictGetUInt32('dw_shop', 'categorytreeid', tuple(shop_id))                                   AS categorytreeid,
         multiIf(logistics = 1, '存储', logistics = 2, '直通', logistics = 3, '直送', '未知')                 AS rsl_logistics,
         categoryid,
         dictGetString('dw_category_info', 'categoryname', (toUInt8(categorytreeid), categoryid))     AS categoryname,
         dictGetString('dw_category_info', 'mid_categoryid', (toUInt8(categorytreeid), categoryid))   AS mid_categoryid,
         dictGetString('dw_category_info', 'mid_categoryname', (toUInt8(categorytreeid),
                                                                categoryid))                          AS mid_categoryname,
         dictGetString('dw_category_info', 'h_categoryid', (toUInt8(categorytreeid), categoryid))     AS h_categoryid,
         dictGetString('dw_category_info', 'h_categoryname', (toUInt8(categorytreeid), categoryid))   AS h_categoryname,
         venderid,
         dictGetString('dw_vender_info', 'vendername', (out_buid, venderid))                          AS vendername,
         dictGetString('dw_vender_info', 'parent_venderid', (out_buid,
                                                             venderid))                               AS parent_venderid,
         dictGetString('dw_vender_info', 'parent_vendername', (out_buid,
                                                               venderid))                             AS parent_vendername,
         multiIf(dc_type = 1, '干货', dc_type = 2, '生鲜', '未知')                                          AS rsl_dctype,
         multiIf(shopformid = 1, '大超', shopformid = 2, '小业态', shopformid = 3, '标超', shopformid = 4, '便利店',
                 shopformid = 4, '仓间', '未知')                                                          AS rsl_shopformid,
         rsl_cost,
         rsl_boxes,
         rsl_qty,
         rsl_drygood_cost,
         rsl_drygood_boxes,
         rsl_drygood_qty,
         rsl_fresh_cost,
         rsl_fresh_boxes,
         rsl_fresh_qty,
         rsl_drygood_supshop_cost,
         rsl_drygood_supshop_boxes,
         rsl_drygood_supshop_qty,
         rsl_drygood_smallshop_cost,
         rsl_drygood_smallshop_boxes,
         rsl_drygood_smallshop_qty,
         rsl_fresh_supshop_cost,
         rsl_fresh_supshop_boxes,
         rsl_fresh_supshop_qty,
         rsl_fresh_smallshop_cost,
         rsl_fresh_smallshop_boxes
  FROM dw_hr.fct_rsl_dc_shop_vender_day;

CREATE VIEW dw_hr.vw_fct_rt_dc_shop_day (stat_year UInt16, stat_month UInt32, stat_day Date, out_buid String, out_buname String, out_shop_id String, out_shopname String, out_provinces_regions String, rt_dctype String, rt_buntype String, in_shop_id String, in_shopname String, in_provinces_regions String, shopformid_type String, rt_datasource String, logistics UInt8, rt_qty Decimal (18, 4), rt_cost Decimal (18, 4), rt_taxcost Decimal (18, 4), rt_shops String, rt_drygood_qty Decimal (18, 4), rt_drygood_cost Decimal (18, 4), rt_drygood_boxes Decimal (18, 4), rt_drygood_shops String, rt_fresh_qty Decimal (18, 4), rt_fresh_cost Decimal (18, 4), rt_fresh_shops String, rt_supshop_cost Decimal (18, 4), rt_supshop_qty Decimal (18, 4), rt_supshop_shops String, rt_smallshop_cost Decimal (18, 4), rt_smallshop_qty Decimal (18, 4), rt_smallshop_shops String, rt_dc_cost Decimal (18, 4), rt_dc_qty Decimal (18, 4), rt_drygood_supshop_cost Decimal (18, 4), rt_drygood_supshop_qty Decimal (18, 4), rt_drygood_supshop_boxes Decimal (18, 4), rt_drygood_supshop_shops String, rt_drygood_smallshop_cost Decimal (18, 4), rt_drygood_smallshop_qty Decimal (18, 4), rt_drygood_smallshop_boxes Decimal (18, 4), rt_drygood_smallshop_shops String, rt_drygood_dc_cost Decimal (18, 4), rt_drygood_dc_qty Decimal (18, 4), rt_drygood_dc_boxes Decimal (18, 4), rt_drygood_dc_shops String, rt_fresh_supshop_cost Decimal (18, 4), rt_fresh_supshop_qty Decimal (18, 4), rt_fresh_supshop_shops String, rt_fresh_smallshop_cost Decimal (18, 4), rt_fresh_smallshop_qty Decimal (18, 4), rt_fresh_smallshop_shops String, rt_fresh_dc_cost Decimal (18, 4), rt_fresh_dc_qty Decimal (18, 4)) AS
  SELECT frt.stat_year,
         frt.stat_month,
         frt.stat_day,
         frt.out_buid,
         dictGetString('dw_buinfo', 'buname', tuple(out_buid))             AS out_buname,
         frt.out_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(out_shop_id))          AS out_shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(out_shop_id)) AS out_provinces_regions,
         multiIf(frt.dctype = 1, '干货', frt.dctype = 2, '生鲜', '未知')         AS rt_dctype,
         multiIf(frt.buntype = 1, '配送', frt.buntype = 3, '返配', frt.buntype = 5, '调拨', frt.buntype = 6, '批发',
                 frt.buntype = 7, '提货', '未知')                              AS rt_buntype,
         frt.in_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(in_shop_id))           AS in_shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(in_shop_id))  AS in_provinces_regions,
         multiIf(frt.shopformid = 1, '大超', frt.shopformid = 2, '小业态', frt.shopformid = 3, '标超', frt.shopformid = 4,
                 '便利店', frt.shopformid = 5, '仓间', '未知')                    AS shopformid_type,
         multiIf(frt.datasource = 1, '全国', frt.datasource = 2, '香港', frt.datasource = 3, '苏果', frt.datasource = 4,
                 'OLE', '未知')                                              AS rt_datasource,
         logistics,
         frt.rt_qty,
         frt.rt_cost,
         frt.rt_taxcost,
         frt.rt_shops,
         rt_drygood_qty,
         rt_drygood_cost,
         rt_drygood_boxes,
         rt_drygood_shops,
         rt_fresh_qty,
         rt_fresh_cost,
         rt_fresh_shops,
         rt_supshop_cost,
         rt_supshop_qty,
         rt_supshop_shops,
         rt_smallshop_cost,
         rt_smallshop_qty,
         rt_smallshop_shops,
         rt_dc_cost,
         rt_dc_qty,
         rt_drygood_supshop_cost,
         rt_drygood_supshop_qty,
         rt_drygood_supshop_boxes,
         rt_drygood_supshop_shops,
         rt_drygood_smallshop_cost,
         rt_drygood_smallshop_qty,
         rt_drygood_smallshop_boxes,
         rt_drygood_smallshop_shops,
         rt_drygood_dc_cost,
         rt_drygood_dc_qty,
         rt_drygood_dc_boxes,
         rt_drygood_dc_shops,
         rt_fresh_supshop_cost,
         rt_fresh_supshop_qty,
         rt_fresh_supshop_shops,
         rt_fresh_smallshop_cost,
         rt_fresh_smallshop_qty,
         rt_fresh_smallshop_shops,
         rt_fresh_dc_cost,
         rt_fresh_dc_qty
  FROM dw_hr.fct_rt_dc_shop_day AS frt;

CREATE VIEW dw_hr.vw_fct_rt_dc_shop_sku_vender_day (stat_year UInt16, stat_month UInt32, stat_day Date, out_buid String, out_buname String, out_shop_id String, out_shopname String, out_provinces_regions String, rt_dctype String, rt_buntype String, in_shop_id String, in_shopname String, in_provinces_regions String, shopformid_type String, rt_datasource String, categoryname String, mid_categoryid String, mid_categoryname String, h_categoryid String, h_categoryname String, p_venderid String, p_vendernm String, rt_qty Decimal (18, 4), rt_cost Decimal (18, 4), rt_taxcost Decimal (18, 4), rt_shops String, rt_drygood_qty Decimal (18, 4), rt_drygood_cost Decimal (18, 4), rt_drygood_boxes Decimal (18, 4), rt_drygood_shops String, rt_fresh_qty Decimal (18, 4), rt_fresh_cost Decimal (18, 4), rt_fresh_shops String, rt_supshop_cost Decimal (18, 4), rt_supshop_qty Decimal (18, 4), rt_supshop_shops String, rt_smallshop_cost Decimal (18, 4), rt_smallshop_qty Decimal (18, 4), rt_smallshop_shops String, rt_dc_cost Decimal (18, 4), rt_dc_qty Decimal (18, 4), rt_drygood_supshop_cost Decimal (18, 4), rt_drygood_supshop_qty Decimal (18, 4), rt_drygood_supshop_boxes Decimal (18, 4), rt_drygood_supshop_shops String, rt_drygood_smallshop_cost Decimal (18, 4), rt_drygood_smallshop_qty Decimal (18, 4), rt_drygood_smallshop_boxes Decimal (18, 4), rt_drygood_smallshop_shops String, rt_drygood_dc_cost Decimal (18, 4), rt_drygood_dc_qty Decimal (18, 4), rt_drygood_dc_boxes Decimal (18, 4), rt_drygood_dc_shops String, rt_fresh_supshop_cost Decimal (18, 4), rt_fresh_supshop_qty Decimal (18, 4), rt_fresh_supshop_shops String, rt_fresh_smallshop_cost Decimal (18, 4), rt_fresh_smallshop_qty Decimal (18, 4), rt_fresh_smallshop_shops String, rt_fresh_dc_cost Decimal (18, 4), rt_fresh_dc_qty Decimal (18, 4)) AS
  SELECT frt.stat_year,
         frt.stat_month,
         frt.stat_day,
         frt.out_buid,
         dictGetString('dw_buinfo', 'buname', tuple(out_buid))                                       AS out_buname,
         frt.out_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(out_shop_id))                                    AS out_shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(out_shop_id))                           AS out_provinces_regions,
         multiIf(frt.dctype = 1, '干货', frt.dctype = 2, '生鲜', '未知')                                   AS rt_dctype,
         multiIf(frt.buntype = 1, '配送', frt.buntype = 3, '返配', frt.buntype = 5, '调拨', frt.buntype = 6, '批发',
                 frt.buntype = 7, '提货', '未知')                                                        AS rt_buntype,
         frt.in_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(in_shop_id))                                     AS in_shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(in_shop_id))                            AS in_provinces_regions,
         multiIf(frt.shopformid = 1, '大超', frt.shopformid = 2, '小业态', frt.shopformid = 3, '标超', frt.shopformid = 4,
                 '便利店', frt.shopformid = 5, '仓间', '未知')                                              AS shopformid_type,
         multiIf(frt.datasource = 1, '全国', frt.datasource = 2, '香港', frt.datasource = 3, '苏果', frt.datasource = 4,
                 'OLE', '未知')                                                                        AS rt_datasource,
         dictGetString('dw_category_info', 'categoryname', (frt.categorytreeid, frt.categoryid))     AS categoryname,
         dictGetString('dw_category_info', 'mid_categoryid', (frt.categorytreeid, frt.categoryid))   AS mid_categoryid,
         dictGetString('dw_category_info', 'mid_categoryname', (frt.categorytreeid,
                                                                frt.categoryid))                     AS mid_categoryname,
         dictGetString('dw_category_info', 'h_categoryid', (frt.categorytreeid, frt.categoryid))     AS h_categoryid,
         dictGetString('dw_category_info', 'h_categoryname', (frt.categorytreeid, frt.categoryid))   AS h_categoryname,
         dictGetString('dw_vender_info', 'parent_venderid', (out_buid, frt.venderid))                AS p_venderid,
         dictGetString('dw_vender_info', 'parent_vendername', (out_buid, frt.venderid))              AS p_vendernm,
         frt.rt_qty,
         frt.rt_cost,
         frt.rt_taxcost,
         frt.rt_shops,
         rt_drygood_qty,
         rt_drygood_cost,
         rt_drygood_boxes,
         rt_drygood_shops,
         rt_fresh_qty,
         rt_fresh_cost,
         rt_fresh_shops,
         rt_supshop_cost,
         rt_supshop_qty,
         rt_supshop_shops,
         rt_smallshop_cost,
         rt_smallshop_qty,
         rt_smallshop_shops,
         rt_dc_cost,
         rt_dc_qty,
         rt_drygood_supshop_cost,
         rt_drygood_supshop_qty,
         rt_drygood_supshop_boxes,
         rt_drygood_supshop_shops,
         rt_drygood_smallshop_cost,
         rt_drygood_smallshop_qty,
         rt_drygood_smallshop_boxes,
         rt_drygood_smallshop_shops,
         rt_drygood_dc_cost,
         rt_drygood_dc_qty,
         rt_drygood_dc_boxes,
         rt_drygood_dc_shops,
         rt_fresh_supshop_cost,
         rt_fresh_supshop_qty,
         rt_fresh_supshop_shops,
         rt_fresh_smallshop_cost,
         rt_fresh_smallshop_qty,
         rt_fresh_smallshop_shops,
         rt_fresh_dc_cost,
         rt_fresh_dc_qty
  FROM dw_hr.fct_rt_dc_shop_sku_vender_day AS frt;

CREATE VIEW dw_hr.vw_fct_rt_dc_shop_sku_vender_mon (stat_year UInt16, stat_month UInt32, out_buid String, out_buname String, out_shop_id String, out_shopname String, out_provinces_regions String, rt_dctype String, rt_buntype String, in_shop_id String, in_shopname String, in_provinces_regions String, shopformid_type String, rt_datasource String, categoryid String, categoryname String, mid_categoryid String, mid_categoryname String, h_categoryid String, h_categoryname String, p_venderid String, p_vendernm String, logistics UInt8, rt_qty Decimal (18, 4), rt_cost Decimal (18, 4), rt_taxcost Decimal (18, 4), rt_shops String, rt_drygood_qty Decimal (18, 4), rt_drygood_cost Decimal (18, 4), rt_drygood_boxes Decimal (18, 4), rt_drygood_shops String, rt_fresh_qty Decimal (18, 4), rt_fresh_cost Decimal (18, 4), rt_fresh_shops String, rt_supshop_cost Decimal (18, 4), rt_supshop_qty Decimal (18, 4), rt_supshop_shops String, rt_smallshop_cost Decimal (18, 4), rt_smallshop_qty Decimal (18, 4), rt_smallshop_shops String, rt_dc_cost Decimal (18, 4), rt_dc_qty Decimal (18, 4), rt_drygood_supshop_cost Decimal (18, 4), rt_drygood_supshop_qty Decimal (18, 4), rt_drygood_supshop_boxes Decimal (18, 4), rt_drygood_supshop_shops String, rt_drygood_smallshop_cost Decimal (18, 4), rt_drygood_smallshop_qty Decimal (18, 4), rt_drygood_smallshop_boxes Decimal (18, 4), rt_drygood_smallshop_shops String, rt_drygood_dc_cost Decimal (18, 4), rt_drygood_dc_qty Decimal (18, 4), rt_drygood_dc_boxes Decimal (18, 4), rt_drygood_dc_shops String, rt_fresh_supshop_cost Decimal (18, 4), rt_fresh_supshop_qty Decimal (18, 4), rt_fresh_supshop_shops String, rt_fresh_smallshop_cost Decimal (18, 4), rt_fresh_smallshop_qty Decimal (18, 4), rt_fresh_smallshop_shops String, rt_fresh_dc_cost Decimal (18, 4), rt_fresh_dc_qty Decimal (18, 4), cost_percent Decimal (18, 6)) AS
  SELECT frt.stat_year,
         frt.stat_month,
         frt.out_buid,
         dictGetString('dw_buinfo', 'buname', tuple(out_buid))                                       AS out_buname,
         frt.out_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(out_shop_id))                                    AS out_shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(out_shop_id))                           AS out_provinces_regions,
         multiIf(frt.dctype = 1, '干货', frt.dctype = 2, '生鲜', '未知')                                   AS rt_dctype,
         multiIf(frt.buntype = 1, '配送', frt.buntype = 3, '返配', frt.buntype = 5, '调拨', frt.buntype = 6, '批发',
                 frt.buntype = 7, '提货', '未知')                                                        AS rt_buntype,
         frt.in_shop_id,
         dictGetString('dw_shop', 'shopname', tuple(in_shop_id))                                     AS in_shopname,
         dictGetString('dw_shop', 'provinces_regions', tuple(in_shop_id))                            AS in_provinces_regions,
         multiIf(frt.shopformid = 1, '大超', frt.shopformid = 2, '小业态', frt.shopformid = 3, '标超', frt.shopformid = 4,
                 '便利店', frt.shopformid = 5, '仓间', '未知')                                              AS shopformid_type,
         multiIf(frt.datasource = 1, '全国', frt.datasource = 2, '香港', frt.datasource = 3, '苏果', frt.datasource = 4,
                 'OLE', '未知')                                                                        AS rt_datasource,
         frt.categoryid,
         dictGetString('dw_category_info', 'categoryname', (frt.categorytreeid, frt.categoryid))     AS categoryname,
         dictGetString('dw_category_info', 'mid_categoryid', (frt.categorytreeid, frt.categoryid))   AS mid_categoryid,
         dictGetString('dw_category_info', 'mid_categoryname', (frt.categorytreeid,
                                                                frt.categoryid))                     AS mid_categoryname,
         dictGetString('dw_category_info', 'h_categoryid', (frt.categorytreeid, frt.categoryid))     AS h_categoryid,
         dictGetString('dw_category_info', 'h_categoryname', (frt.categorytreeid, frt.categoryid))   AS h_categoryname,
         dictGetString('dw_vender_info', 'parent_venderid', (out_buid, frt.venderid))                AS p_venderid,
         dictGetString('dw_vender_info', 'parent_vendername', (out_buid, frt.venderid))              AS p_vendernm,
         frt.logistics,
         frt.rt_qty,
         frt.rt_cost,
         frt.rt_taxcost,
         frt.rt_shops,
         rt_drygood_qty,
         rt_drygood_cost,
         rt_drygood_boxes,
         rt_drygood_shops,
         rt_fresh_qty,
         rt_fresh_cost,
         rt_fresh_shops,
         rt_supshop_cost,
         rt_supshop_qty,
         rt_supshop_shops,
         rt_smallshop_cost,
         rt_smallshop_qty,
         rt_smallshop_shops,
         rt_dc_cost,
         rt_dc_qty,
         rt_drygood_supshop_cost,
         rt_drygood_supshop_qty,
         rt_drygood_supshop_boxes,
         rt_drygood_supshop_shops,
         rt_drygood_smallshop_cost,
         rt_drygood_smallshop_qty,
         rt_drygood_smallshop_boxes,
         rt_drygood_smallshop_shops,
         rt_drygood_dc_cost,
         rt_drygood_dc_qty,
         rt_drygood_dc_boxes,
         rt_drygood_dc_shops,
         rt_fresh_supshop_cost,
         rt_fresh_supshop_qty,
         rt_fresh_supshop_shops,
         rt_fresh_smallshop_cost,
         rt_fresh_smallshop_qty,
         rt_fresh_smallshop_shops,
         rt_fresh_dc_cost,
         rt_fresh_dc_qty,
         toDecimal64(frt.rt_cost, 6) / toDecimal64(frt.rt_outshop_cost, 4)                           AS cost_percent
  FROM dw_hr.fct_rt_dc_shop_sku_vender_mon AS frt;


